name: build

on: [pull_request]

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, zig cc]
        include:
          - os: windows-latest
            compiler: cl.exe

    name: compile
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - if: matrix.os == 'windows-latest' && matrix.compiler == 'gcc'
        uses: csukuangfj/setup-mingw@v2.2.1
        with:
          version: '12.2.0'

      - if: matrix.compiler == 'cl.exe' && matrix.os == 'windows-latest'
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - if: matrix.compiler == 'zig cc'
        uses: goto-bus-stop/setup-zig@v2

      - name: build
        run: ${{ matrix.compiler }} -o scanner.o -I./src -c src/scanner.c
